/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT1_8 (coord A1), P1_8/J9[12]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[11]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_23 (coord B7), P0_23/J2[2]/J8[5]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RXD_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RXD_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RXD_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT0_22 (coord B8), P0_22/J1[16]/J2[9]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TXD_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TXD_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TXD_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT3_14 (coord H17), P3_14/J2[4]/J3[11]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_WIFI_RST_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_WIFI_RST_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_WIFI_RST_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_WIFI_RST_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_WIFI_RST_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_WIFI_RST_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
